# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nba-player-longevity

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ibti2/
        username: ${{ secrets.AzureAppService_ContainerUsername_52b7a1a3650a4ae9988e87a4773df700 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d4919515249c4cec90bebe14af4d36f5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ibti2/${{ secrets.AzureAppService_ContainerUsername_52b7a1a3650a4ae9988e87a4773df700 }}/nba-prediction-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nba-player-longevity'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_79eaa694a64f4627bb8fb72087c52a9e }}
        images: 'ibti2/${{ secrets.AzureAppService_ContainerUsername_52b7a1a3650a4ae9988e87a4773df700 }}/nba-prediction-api:${{ github.sha }}'